//+------------------------------------------------------------------+
//| Ma_Rsi_Phase2.mq5                                               |
//| Phase 2: Regime-adaptive indicator weight profiles module       |
//| Self-contained helper module — do not modify Ma_Rsi.mq5 here    |
//+------------------------------------------------------------------+
#property copyright "Auto-generated by builder-phase2-weights"
#property version   "1.00"
#include <Trade\Trade.mqh>

// Weight profile struct
struct WeightProfile
{
  double ma;   // EMA crossover weight
  double macd; // MACD weight
  double adx;  // ADX weight (trend strength)
  double rsi;  // RSI weight
  double bb;   // Bollinger Bands weight
};

// Default predefined profiles
WeightProfile trend_weights = {0.35, 0.30, 0.20, 0.05, 0.10};
WeightProfile range_weights = {0.10, 0.00, 0.00, 0.40, 0.30};
WeightProfile highvol_weights = {0.20, 0.20, 0.00, 0.20, 0.30};
WeightProfile lowvol_weights = {0.30, 0.10, 0.00, 0.30, 0.20};

// Inputs (phase 2)
input bool use_adaptive_weights = false; // Enable regime-based weight profiles

// Base weights (used when adaptive is OFF)
input double weightMA_base   = 0.40;
input double weightBB_base   = 0.10;
input double weightRSI_base  = 0.30;
input double weightMACD_base = 0.20;

// Trend regime weights
input double weightMA_trend   = 0.35;
input double weightMACD_trend = 0.30;
input double weightADX_trend  = 0.20; // mapped into adx field
input double weightRSI_trend  = 0.05;
input double weightBB_trend   = 0.10;

// Range regime weights
input double weightRSI_range = 0.40;
input double weightBB_range  = 0.30;
input double weightMA_range  = 0.10;

// High vol regime weights (these are loosely mapped)
input double weightATR_highvol    = 0.30; // will be blended into adx/bb/macd as reasonable
input double weightBB_highvol     = 0.30;
input double weightTrend_highvol  = 0.20;
input double weightOsc_highvol    = 0.20;

// Low vol regime weights
input double weightMA_lowvol  = 0.30;
input double weightOsc_lowvol = 0.30;
input double weightBB_lowvol  = 0.20;
input double weightATR_lowvol = 0.20;

// Smoothing & thresholds
input double regime_weight_alpha = 0.92; // EMA smoothing for regime transitions
input double adx_enter = 28.0; // ADX to enter trending regime
input double adx_exit  = 22.0; // ADX to exit trending regime

// Internal smoothing state
double R_trend_smooth = 0.5; // initial value

// Helper: normalize a WeightProfile so components sum to 1 (if total > 0)
void NormalizeProfile(WeightProfile &p)
{
  double sum = p.ma + p.macd + p.adx + p.rsi + p.bb;
  if(sum <= 0.0)
  {
    // fallback to equal weights
    p.ma = p.macd = p.adx = p.rsi = p.bb = 0.2;
    return;
  }
  p.ma   /= sum;
  p.macd /= sum;
  p.adx  /= sum;
  p.rsi  /= sum;
  p.bb   /= sum;
}

// Utility: linear interpolation between two doubles
double Lerp(double a,double b,double t){ return a + t*(b-a); }

// Utility: interpolate between two profiles
WeightProfile ProfileLerp(const WeightProfile &a,const WeightProfile &b,double t)
{
  WeightProfile r;
  r.ma   = Lerp(a.ma,b.ma,t);
  r.macd = Lerp(a.macd,b.macd,t);
  r.adx  = Lerp(a.adx,b.adx,t);
  r.rsi  = Lerp(a.rsi,b.rsi,t);
  r.bb   = Lerp(a.bb,b.bb,t);
  return r;
}

// GetRegimeWeights: compute regime-adjusted weight profile
// regime: 0=auto (use ADX/vol heuristics), 1=trend, 2=range, 3=highvol, 4=lowvol
WeightProfile GetRegimeWeights(int regime, double adx_value, double atr_value, double vol_metric)
{
  // If user provided explicit regime mapping, respect it
  WeightProfile chosen;

  // Start from predefined profiles but allow inputs to override some
  // Build trend and range profiles from inputs to reflect UI-configurable values
  WeightProfile trend;
  trend.ma   = weightMA_trend;
  trend.macd = weightMACD_trend;
  trend.adx  = weightADX_trend;
  trend.rsi  = weightRSI_trend;
  trend.bb   = weightBB_trend;
  NormalizeProfile(trend);

  WeightProfile range;
  range.ma   = weightMA_range;
  range.macd = 0.0;
  range.adx  = 0.0;
  range.rsi  = weightRSI_range;
  range.bb   = weightBB_range;
  NormalizeProfile(range);

  // High/low vol profiles constructed from inputs
  WeightProfile highv;
  highv.ma   = weightTrend_highvol;    // trend-like contribution
  highv.macd = weightATR_highvol * 0.5; // split ATR into macd-ish and adx-ish
  highv.adx  = weightATR_highvol * 0.5;
  highv.rsi  = weightOsc_highvol;
  highv.bb   = weightBB_highvol;
  NormalizeProfile(highv);

  WeightProfile lowv;
  lowv.ma   = weightMA_lowvol;
  lowv.macd = 0.10; // small
  lowv.adx  = weightATR_lowvol * 0.5;
  lowv.rsi  = weightOsc_lowvol;
  lowv.bb   = weightBB_lowvol;
  NormalizeProfile(lowv);

  // If explicit regime requested, return it directly (with smoothing kept outside)
  if(regime==1) return trend;
  if(regime==2) return range;
  if(regime==3) return highv;
  if(regime==4) return lowv;

  // Auto mode: determine trend confidence from ADX
  double R_trend_raw = 0.0;
  if(adx_value >= adx_enter) R_trend_raw = 1.0;
  else if(adx_value <= adx_exit) R_trend_raw = 0.0;
  else R_trend_raw = (adx_value - adx_exit) / (adx_enter - adx_exit);

  // Smooth the trend confidence using EMA
  R_trend_smooth = regime_weight_alpha * R_trend_smooth + (1.0 - regime_weight_alpha) * R_trend_raw;

  // Volatility influence: use ATR or vol_metric to blend toward high/low vol
  // For simplicity, vol_metric is expected >0; we normalize heuristically
  double vol_conf = 0.5; // 0=low vol,1=high vol
  if(vol_metric > 0.0)
  {
    // user-provided metric: larger -> higher vol. Use soft scaling
    double v = vol_metric;
    // scale v into [0,1] by heuristic: assume typical range up to some multiple of ATR
    vol_conf = 1.0 - 1.0/(1.0+v);
    if(vol_conf<0) vol_conf=0; if(vol_conf>1) vol_conf=1;
  }

  // Blend profiles: first between range (low trend) and trend by R_trend_smooth
  WeightProfile blended = ProfileLerp(range, trend, R_trend_smooth);

  // Then blend toward highvol/lowvol based on vol_conf
  WeightProfile vol_blend = ProfileLerp(lowv, highv, vol_conf);

  // Final blend: give moderate weight to volatility (e.g., 0.35), rest to trend-range
  double vol_influence = 0.35;
  WeightProfile finalp = ProfileLerp(blended, vol_blend, vol_influence);

  NormalizeProfile(finalp);
  return finalp;
}

// Utility to produce base profile when adaptive is OFF
WeightProfile BaseProfileFromInputs()
{
  WeightProfile p;
  p.ma   = weightMA_base;
  p.macd = weightMACD_base;
  p.adx  = 0.0; // base ADX weight not exposed in base inputs; distribute to others
  p.rsi  = weightRSI_base;
  p.bb   = weightBB_base;
  // Redistribute adx=0 proportionally so sum becomes 1
  NormalizeProfile(p);
  return p;
}

// Example function demonstrating integration with indicator confidences
// indicators_conf: array of confidences for [ma, macd, adx, rsi, bb] in [0..1]
// current_regime: as in GetRegimeWeights (0=auto)
// adx_value, atr_value, vol_metric are used to compute regime weights
// returns total normalized score and fills out weighted contributions (out array)
double ComputeCombinedSignal(const double indicators_conf[], int current_regime, double adx_value, double atr_value, double vol_metric, double out_contrib[])
{
  WeightProfile wp;
  if(use_adaptive_weights)
    wp = GetRegimeWeights(current_regime, adx_value, atr_value, vol_metric);
  else
    wp = BaseProfileFromInputs();

  // Multiply confidences by weights
  double contrib[5];
  contrib[0] = indicators_conf[0] * wp.ma;
  contrib[1] = indicators_conf[1] * wp.macd;
  contrib[2] = indicators_conf[2] * wp.adx;
  contrib[3] = indicators_conf[3] * wp.rsi;
  contrib[4] = indicators_conf[4] * wp.bb;

  // sum and normalize to [0..1]
  double sum = 0.0;
  for(int i=0;i<5;i++) sum += contrib[i];
  if(sum > 0.0)
  {
    for(int i=0;i<5;i++) out_contrib[i] = contrib[i]/sum;
    return 1.0; // indicates normalized
  }
  else
  {
    // zero signal
    for(int i=0;i<5;i++) out_contrib[i]=0.0;
    return 0.0;
  }
}

// Small helper to format and show profile in terminal/Comment
string ProfileToString(const WeightProfile &p)
{
  string s;
  s = StringFormat("MA:%.3f MACD:%.3f ADX:%.3f RSI:%.3f BB:%.3f", p.ma, p.macd, p.adx, p.rsi, p.bb);
  return s;
}

// Example OnTick stub showing how this module would be used
void OnTick_Example()
{
  // Placeholder example: in real integration the caller would compute these
  double indicators_conf[5] = {0.8, 0.6, 0.7, 0.2, 0.5}; // example confidences
  int current_regime = 0; // auto
  double adx_value = iADX(_Symbol,PERIOD_CURRENT,14,PRICE_CLOSE,MODE_MAIN,0);
  double atr_value = iATR(_Symbol,PERIOD_CURRENT,14,0);
  double vol_metric = atr_value; // simple vol proxy

  double out_contrib[5];
  ComputeCombinedSignal(indicators_conf,current_regime,adx_value,atr_value,vol_metric,out_contrib);

  WeightProfile wp = use_adaptive_weights ? GetRegimeWeights(current_regime,adx_value,atr_value,vol_metric) : BaseProfileFromInputs();

  // Show current profile and contributions on chart
  string info = StringFormat("Adaptive:%s ADX:%.2f ATR:%.5f\nProfile: %s\nContrib MA:%.2f MACD:%.2f ADX:%.2f RSI:%.2f BB:%.2f",
                            use_adaptive_weights?"ON":"OFF", adx_value, atr_value, ProfileToString(wp), out_contrib[0], out_contrib[1], out_contrib[2], out_contrib[3], out_contrib[4]);
  Comment(info);
}

//+------------------------------------------------------------------+
// End of Ma_Rsi_Phase2.mq5
//+------------------------------------------------------------------+